---
- name: Install Kerberos and LDAP clients
  yum: name={{ item }} state=present
  with_items:
    - krb5-workstation
    - openldap-clients

- name: Configure Kerberos integration with AD
  template: src=krb5.conf dest=/etc/krb5.conf
            owner=root group=root mode=644

- name: Get kerberos ticket with the sambe keytab
  command: kinit -k -t /etc/krb5.keytab {{ ansible_hostname | upper }}$\@{{ adauth_realm }}
  args:
    creates: /tmp/krb5cc_0
